export const MEDIA_TYPE_ABOUT_US = 'ABOUT_US';
export const MEDIA_TYPE_NEWS = 'NEWS';
export const MEDIA_TYPE_BLOG = 'BLOG';
export const MEDIA_TYPE_BLOG_ARTICLE = 'BLOG_ARTICLE';
export const MEDIA_TYPE_PROJECT = 'PROJECT';
export const MEDIA_TYPE_PRODUCT = 'PRODUCT';
export const MEDIA_TYPE_REVIEW = 'REVIEW';
export const MEDIA_TYPE_REVIEW_AVATAR = 'REVIEW_OWNER_AVATAR';
export const OTHER = 'OTHER';
export const MEDIA_SOURCE_TYPES = [
  MEDIA_TYPE_ABOUT_US,
  MEDIA_TYPE_NEWS,
  MEDIA_TYPE_REVIEW_AVATAR,
  MEDIA_TYPE_REVIEW,
  MEDIA_TYPE_BLOG,
  MEDIA_TYPE_PRODUCT,
  MEDIA_TYPE_PROJECT,
  OTHER,
];

export const MEDIA_TYPES_VIDEO = 'VIDEO';
export const MEDIA_TYPES_PHOTO = 'IMAGE';
export const MEDIA_TYPES = [MEDIA_TYPES_VIDEO, MEDIA_TYPES_PHOTO];
